# Generated by Django 5.2.15 on 2026-07-07 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutgoingNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("events", "Événements"),
                            ("news", "Actualités"),
                            ("alerts", "Alertes"),
                        ],
                        max_length=20,
                        verbose_name="sujet",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("alert", "Alerte"), ("normal", "Normale")],
                        default="normal",
                        max_length=10,
                        verbose_name="priorité",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="titre")),
                ("body", models.CharField(blank=True, max_length=300, verbose_name="texte")),
                ("url", models.CharField(default="/", max_length=300, verbose_name="lien")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "À envoyer"),
                            ("sending", "Envoi en cours"),
                            ("done", "Envoyée"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="état",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="créée le"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="envoyée le")),
            ],
            options={
                "verbose_name": "notification sortante",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("endpoint", models.URLField(max_length=500, unique=True, verbose_name="endpoint")),
                ("p256dh", models.CharField(max_length=200, verbose_name="clé p256dh")),
                ("auth", models.CharField(max_length=100, verbose_name="clé auth")),
                ("topics", models.JSONField(default=list, verbose_name="sujets")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="créé le"),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="dernier succès"),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(default=0, verbose_name="échecs consécutifs"),
                ),
            ],
            options={
                "verbose_name": "abonnement aux notifications",
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "À livrer"),
                            ("sent", "Livrée"),
                            ("failed", "En échec"),
                            ("gone", "Abonnement disparu"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="push.outgoingnotification",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="push.pushsubscription",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("notification", "subscription"), name="delivery_unique"
                    )
                ],
            },
        ),
    ]
