# Generated by Django 5.2.15 on 2026-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MirroredEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "gancio_id",
                    models.PositiveIntegerField(unique=True, verbose_name="identifiant Gancio"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("starts_at", models.DateTimeField(verbose_name="début")),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="fin")),
                ("place_name", models.CharField(blank=True, max_length=200, verbose_name="lieu")),
                (
                    "place_address",
                    models.CharField(blank=True, max_length=300, verbose_name="adresse"),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="étiquettes")),
                ("image_url", models.URLField(blank=True, max_length=500, verbose_name="image")),
                (
                    "image_alt",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="texte alternatif de l'image"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, max_length=500, verbose_name="page Gancio"),
                ),
                (
                    "notified",
                    models.BooleanField(default=False, verbose_name="notification envoyée"),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="première synchronisation"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="dernière synchronisation"),
                ),
            ],
            options={
                "verbose_name": "événement",
                "ordering": ["starts_at"],
            },
        ),
    ]
