# Generated by Django 5.2.15 on 2026-07-07 15:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="courriel de notification"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="departments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="agents",
                    ),
                ),
            ],
            options={
                "verbose_name": "service municipal",
                "verbose_name_plural": "services municipaux",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable, sert de service_code Open311.",
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.department",
                        verbose_name="service destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=20, unique=True, verbose_name="référence"),
                ),
                ("description", models.TextField(max_length=4000, verbose_name="description")),
                ("latitude", models.FloatField(blank=True, null=True, verbose_name="latitude")),
                ("longitude", models.FloatField(blank=True, null=True, verbose_name="longitude")),
                ("address", models.CharField(blank=True, max_length=300, verbose_name="adresse")),
                (
                    "location_hint",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="précision sur l'emplacement"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "À traiter"),
                            ("in_progress", "En cours"),
                            ("resolved", "Résolu"),
                            ("rejected", "Rejeté"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=300, verbose_name="motif de rejet"),
                ),
                (
                    "reporter_email",
                    models.EmailField(
                        blank=True,
                        help_text="Jamais publié, purgé à l'anonymisation.",
                        max_length=254,
                        verbose_name="courriel du déclarant",
                    ),
                ),
                (
                    "created_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP de création"
                    ),
                ),
                (
                    "created_user_agent",
                    models.CharField(blank=True, max_length=300, verbose_name="user-agent"),
                ),
                ("tracking_token", models.CharField(max_length=64, verbose_name="jeton de suivi")),
                (
                    "publication_state",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de modération"),
                            ("published", "Publié"),
                            ("hidden", "Masqué"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="publication",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="créé le"),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="clos le")),
                (
                    "anonymized_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="anonymisé le"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.category",
                        verbose_name="catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "signalement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="signalements/%Y/%m/", verbose_name="photo")),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="signalements/miniatures/%Y/%m/", verbose_name="miniature"
                    ),
                ),
                (
                    "moderation_state",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="modération",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        default="Photo jointe au signalement",
                        max_length=300,
                        verbose_name="texte alternatif",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="reports.report",
                        verbose_name="signalement",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo de signalement",
            },
        ),
    ]
