# Generated by Django 5.2.15 on 2026-07-07 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_categories_par_defaut"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("new", "À traiter"),
                            ("in_progress", "En cours"),
                            ("resolved", "Résolu"),
                            ("rejected", "Rejeté"),
                        ],
                        max_length=20,
                        verbose_name="ancien statut",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("new", "À traiter"),
                            ("in_progress", "En cours"),
                            ("resolved", "Résolu"),
                            ("rejected", "Rejeté"),
                        ],
                        max_length=20,
                        verbose_name="nouveau statut",
                    ),
                ),
                (
                    "public_comment",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="commentaire public"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(blank=True, max_length=500, verbose_name="photo jointe"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="créée le"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="reports.report",
                        verbose_name="signalement",
                    ),
                ),
            ],
            options={
                "verbose_name": "mise à jour de signalement",
                "ordering": ["created_at"],
            },
        ),
    ]
